version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: easeai-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: easeai
      POSTGRES_USER: easeai_user
      POSTGRES_PASSWORD: easeai_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U easeai_user -d easeai"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local