"""update sql models

Revision ID: 8968f218bc90
Revises: 3307ce2dd132
Create Date: 2025-07-03 13:28:09.283396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8968f218bc90'
down_revision: Union[str, Sequence[str], None] = '3307ce2dd132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentation_plans', 'outline')
    op.drop_column('presentation_plans', 'key_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentation_plans', sa.Column('key_messages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('presentation_plans', sa.Column('outline', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
